### ISSUE TITLE
[Windows] Not finding QtGui dlls

### ISSUE THREAD

**Issue by Mimoja** [Midar/objqt#4]
Using the Makefile in verbose:

+ clang++ -o libobjqt.dll .QtCore_QtCore.lib.a.objs/QtChildEvent.lib.o .QtCore_QtCore.lib.a.objs/QtCoreApplication.lib.o .QtCore_QtCore.lib.a.objs/QtEvent.lib.o .QtCore_QtCore.lib.a.objs/QtObject.lib.o .QtCore_QtCore.lib.a.objs/QtThread.lib.o .QtGui_QtGui.lib.a.objs/QtGUIApplication.lib.o .QtGui_QtGui.lib.a.objs/QtPaintDevice.lib.o .QtWidgets_QtWidgets.lib.a.objs/QtAbstractButton.lib.o .QtWidgets_QtWidgets.lib.a.objs/QtAction.lib.o .QtWidgets_QtWidgets.lib.a.objs/QtApplication.lib.o .QtWidgets_QtWidgets.lib.a.objs/QtPushButton.lib.o .QtWidgets_QtWidgets.lib.a.objs/QtWidget.lib.o .common_common.lib.a.objs/OFDataArray+QByteArray.lib.o .common_common.lib.a.objs/OFString+QString.lib.o -shared -Wl,--export-all-symbols,--out-implib,libobjqt.dll.a -Wl,--allow-multiple-definition -Wl,-rpath,/mingw64/lib -L/mingw64/lib -lobjfw -lm -lws2_32 -LG:/msys64/mingw64/lib -lQt5Core -lole32 -luuid -lws2_32 -ladvapi32 -lshell32 -luser32 -lkernel32 -lmpr -licuin -licuuc -licudt -lwinmm -lz -lpcre16 -LG:/msys64/mingw64/lib -LC:/repo/mingw-w64-qt5/src/x86_64/qtbase/lib -LC:/building/msys64/mingw64/lib -LG:/msys64/mingw64/lib -lQt5Gui -lcomdlg32 -loleaut32 -limm32 -lwinmm -lws2_32 -lole32 -luuid -ladvapi32 -lglu32 -lopengl32 -lgdi32 -luser32 C:/repo/mingw-w64-qt5/src/x86_64/qtbase/lib/libQt5Core.dll.a -lpng16 -lharfbuzz -lz -lQt5Core -lole32 -luuid -lws2_32 -ladvapi32 -lshell32 -luser32 -lkernel32 -lmpr -licuin -licuuc -licudt -lwinmm -lz -lpcre16 -LG:/msys64/mingw64/lib -LC:/repo/mingw-w64-qt5/src/x86_64/qtbase/lib -LG:/msys64/mingw64/lib -LC:/repo/mingw-w64-qt5/src/x86_64/qtbase/lib -LC:/building/msys64/mingw64/lib -LG:/msys64/mingw64/lib -lQt5Widgets -lcomdlg32 -loleaut32 -limm32 -lwinmm -lws2_32 -lole32 -luuid -ladvapi32 -lglu32 -lopengl32 -lgdi32 -luser32 C:/repo/mingw-w64-qt5/src/x86_64/qtbase/lib/libQt5Gui.dll.a C:/repo/mingw-w64-qt5/src/x86_64/qtbase/lib/libQt5Core.dll.a -lshell32 -luxtheme -ldwmapi -lQt5Gui -lcomdlg32 -loleaut32 -limm32 -lwinmm -lws2_32 -lole32 -luuid -ladvapi32 -lglu32 -lopengl32 -lgdi32 -luser32 C:/repo/mingw-w64-qt5/src/x86_64/qtbase/lib/libQt5Core.dll.a -lpng16 -lharfbuzz -lz -lQt5Core -lole32 -luuid -lws2_32 -ladvapi32 -lshell32 -luser32 -lkernel32 -lmpr -licuin -licuuc -licudt -lwinmm -lz -lpcre16
clang++.exe: error: no such file or directory: 'C:/repo/mingw-w64-qt5/src/x86_64/qtbase/lib/libQt5Core.dll.a'
clang++.exe: error: no such file or directory: 'C:/repo/mingw-w64-qt5/src/x86_64/qtbase/lib/libQt5Gui.dll.a'
clang++.exe: error: no such file or directory: 'C:/repo/mingw-w64-qt5/src/x86_64/qtbase/lib/libQt5Core.dll.a'
clang++.exe: error: no such file or directory: 'C:/repo/mingw-w64-qt5/src/x86_64/qtbase/lib/libQt5Core.dll.a'
+ err=1
+ printf 'Failed to link libobjqt.dll!\n'
Failed to link libobjqt.dll!
+ exit 1
make[3]: *** [../buildsys.mk:242: libobjqt.dll] Fehler 1
make[2]: *** [../buildsys.mk:120: all] Fehler 2
+ exit 2
make[1]: *** [buildsys.mk:130: src] Fehler 2
make: *** [buildsys.mk:118: all] Fehler 2

notice the C:/repo/mingw-w64-qt5/src/x86_64/qtbase/lib/libQt5Core.dll.a that derives from $Qt5Gui_LIBS
It is used in configure.ac, but where is it set? I assume, it is the place, where msys2 Qt was compiled, but not the one it was installed to...

**Comment by Mimoja** [comment]
Error lies within pkgconfig:
$ pkg-config.exe --libs "Qt5Gui >= 5.5"
-LG:/msys64/mingw64/lib -LC:/repo/mingw-w64-qt5/src/x86_64/qtbase/lib -LC:/building/msys64/mingw64/lib -LG:/msys64/mingw64/lib -lQt5Gui -lcomdlg32 -loleaut32 -limm32 -lwinmm -lws2_32 -lole32 -luuid -ladvapi32 -lglu32 -lopengl32 -lgdi32 -luser32 C:/repo/mingw-w64-qt5/src/x86_64/qtbase/lib/libQt5Core.dll.a -lpng16 -lharfbuzz -lz -lQt5Core -lole32 -luuid -lws2_32 -ladvapi32 -lshell32 -luser32 -lkernel32 -lmpr -licuin -licuuc -licudt -lwinmm -lz -lpcre16

**Comment by Mimoja** [comment]
"pkg-config" is broken. Use mingw-w64-x86_64-pkg-config instead

**Comment by Midar** [comment]
That sounds like pkg-config and mingw-w64-x86_64-pkg-config are different, even though they shouldn't on mingw-w64-x86_64. Is there maybe a second pkg-config that has preference in the path over the proper one?

**Comment by Mimoja** [comment]
They are different. pkg-config is used to build mingw packages and broken on every other package, as it will leake hardcoded library paths
